branch-defaults:
  master:
    environment: switchtwo-prod
global:
  application_name: switchtwo
  default_ec2_keyname: javabin
  default_region: eu-central-1
  profile: javabin
  sc: git
deploy:
  artifact: app.zip